version: "3.8"

services:
  backstage.app:
    image: backstage:latest
    build:
      context: backstagedemo/
      dockerfile: packages/backend/Dockerfile
    ports:
      - 7007:7007

  backstage.db:
    image: library/postgres:11
    container_name: backstage.db
    environment:
      TZ: Europe/Amsterdam
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: backstage123!
      POSTGRES_DB: backstage
    ports:
      - 5432:5432
    volumes:
      - backstage_db_data:/var/lib/postgresql/data
    restart: always

volumes:
  backstage_db_data:
