name: Build docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
defaults:
  run:
    working-directory: ./backstagedemo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    
    - name: Install yarn
      run: yarn install -g 
     
    - name: yarn build+install
      run: |
          yarn install --frozen-lockfile
          yarn tsc
          yarn build
      
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: "crjacobapps.azurecr.io"
        username: "crjacobapps"
        password: ${{ secrets.REGISTRY_PASSWORD }}  
    
    - run: |
        docker image build . --file packages/backend/Dockerfile --tag crjacobapps.azurecr.io/backstage:latest
        docker push crjacobapps.azurecr.io/backstage:latest
        #docker image build . --file packages/backend/Dockerfile --tag crjacobapps.azurecr.io/backstage:${{ github.sha }}
        #docker push crjacobapps.azurecr.io/backstage:${{ github.sha }}
